version: '3.8'

services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    environment:
      EULA: "TRUE"
      MEMORY: 2G
    ports:
      - "25565:25565"
    volumes:
      - ./minecraft-server:/data

  geysermc:
    image: itzg/bungeecord
    container_name: geysermc
    ports:
      - "19132:19132/udp"
    environment:
      - Geyser-Spigot
    volumes:
      - ./geyser-config:/server/plugins/Geyser-Spigot
    depends_on:
      - minecraft-server

networks:
  default:
    driver: bridge
